;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	helm-show-kill-ring
	indent-for-tab-command
	kill-region
	typescript-insert-and-autoconvert-to-template
	typescript-insert-and-indent
	))

(setq mc/cmds-to-run-once
      '(
	electric-pair-delete-pair
	helm-M-x
	helm-buffers-list
	))
